---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7

Naming/FileName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
